# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Chart-Radial
version:      0.01
version_from: lib/GD/Chart/Radial.pm
installdirs:  site
requires:
    GD:                            2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
