--- #YAML:1.0
name:                     GD-Chart-Radial
version:                  0.09
abstract:                 Plot and output Radial or Radar charts using the GD library
author:
  - Barbie <barbie@missbarbell.co.uk>
  - Aaron J Trevena <aaron@droogs.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  GD:                     2.00
recommends:
  Digest::MD5:            0
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  GD::Chart::Radial:
    file:     lib/GD/Chart/Radial.pm
    version:  0.09

no_index:
  directory:
    - t
    - examples


resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  homepage:   http://stats.cpantesters.org
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=GD-Chart-Radial
  repository: http://github.com/barbie/gd-chart-radial

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
